system = UNKNOWN

include config/Make.$(system)

SOURCE =  main.f iqpackd.f rest.f form.f numerov.f sgi.f cc.f laguer.f  vmat.f first.f gpuvdirect.f \
    ipmhf.f fc.f hf.f vtail.f cisi.f hydr.f processt.f plql.f \
    corratom.f  derivative.f dmatr.f length.f multidipole.f  photo.f \
    velocity.f jnt.f step.f over.f hylleraas.f  posvmat.f positron.f \
    fit_rgrid.f redefine.f coul90.f rs6000.f bmatr.f polyborn.f lvborn.f \
    bes.f e2e.f  gos.f  tdgos.f blength.f jones.f lesech.f h2.f noblegas.f \
    e2e2.f radial2.f b2matr.f xmatr.f coefsS.f coefsP.f coefsD.f coefsF.f \
    coefsG.f coefsH.f coefsI.f \
     newcoefs7.f newcoefs8.f newcoefs9.f newcoefs10.f\
    newcoefs11.f newcoefs12.f newcoefs13.f newcoefs14.f newcoefs15.f \
    newcoefs16.f newcoefs17.f newcoefs18.f newcoefs19.f newcoefs20.f \
    andrey.f tmatccc.f lithium.f sbt.f redistribute.f alex.f logam.f 

F90SOURCE = eremenko.f90

OBJDIR=$(PWD)/$(system)/obj/$(PRECISION)
HELIUM_OBJDIR=obj/helium/$(PRECISION)
ATOM_OBJDIR=obj/atom/$(PRECISION)

#FC := mpifort
#a :=  -Mllvm -mp -Mpreprocess -O2 -Iatom -Ihelium -Ihelium/$(OBJDIR) -module $(OBJDIR) -mcmodel=medium
#aO1 :=  -Mllvm -mp -Mpreprocess -O1 -Iatom -Ihelium -Ihelium/$(OBJDIR) -module $(OBJDIR) -mcmodel=medium
#aGPU := -Mllvm -mp -O2 -Minfo=accel -acc -ta=tesla:cc35,cc50,cc60,nordc -mcmodel=medium -Mpreprocess -Iatom -Ihelium -Ihelium/$(OBJDIR) -module $(OBJDIR)
#l := -Mllvm -acc -mp  -L$(MKLROOT)/lib/intel64 -lmkl_scalapack_lp64 -lmkl_blacs_openmpi_lp64 -lmkl_gf_lp64 -lmkl_intel_thread -lmkl_core  -pgf90libs  

a:= $(FCFLAGS_OPT2) -Iatom -Ihelium -I$(OBJDIR) $(FCFLAGS_MODFLAG) $(OBJDIR)
aO1 := $(FCFLAGS_OPT1) -Iatom -Ihelium -I$(OBJDIR) $(FCFLAGS_MODFLAG) $(OBJDIR)
aGPU := $(FCFLAGS_GPU) -Iatom -Ihelium -I$(OBJDIR) $(FCFLAGS_MODFLAG) $(OBJDIR)
l := $(LDFLAGS)

ifeq ($(PRECISION),double)
  a := $(a) $(FCFLAGS_REAL8)
#  pga := -r8  
  aO1 := $(aO1) $(FCFLAGS_REAL8)
  aGPU := $(aGPU) $(FCFLAGS_REAL8)
else
#  pga := -r4  
  a := $(a)  #-align array32byte #no need for this if rest.f is compiled with -O0
  aO1 := $(aO1)
  aGPU := $(aGPU)
endif

a := $(a) -DNEW_SLEEPY_BARRIER -D_$(PRECISION)
aO1 := $(aO1) -DNEW_SLEEPY_BARRIER -D_$(PRECISION)

OBJS=$(SOURCE:%.f=$(OBJDIR)/%.o) $(F90SOURCE:%.f90=$(OBJDIR)/%.o)

export a
export FC
export PRECISION
export OBJDIR
export aGPU

#info:
#	echo $(OBJECTDIR)
#	echo $(OBJS)

#ccc:  atom/hflib.a helium/helib.a $(OBJS) tmatccc.o  $(OBJDIR)
.PHONY: $(OBJDIR)/helib.a  $(OBJDIR)/hflib.a ccc 
ccc:  $(OBJDIR)/hflib.a $(OBJDIR)/helib.a $(OBJS)
      ifeq ($(PRECISION),double)
	$(FC) $a  $(OBJS) $(OBJDIR)/hflib.a $(OBJDIR)/helib.a $l -o $(PWD)/$(system)/bin/cccd
      else
	$(FC) $a  $(OBJS) $(OBJDIR)/hflib.a $(OBJDIR)/helib.a $l -o $(PWD)/$(system)/bin/cccs
      endif

cco: $e tmatcco.o de.o atom/hflib.a helium/helib.a
	$(FC) $a $e de.o tmatcco.o atom/hflib.a helium/helib.a -lmkl -lmkl_lapack -o cco

clean:
	rm -f $(OBJDIR)/*
	rm -f *.o
	$(MAKE) -C helium clean
	$(MAKE) -C atom clean

$(OBJDIR)/helib.a:
	$(MAKE) -C helium

$(OBJDIR)/hflib.a:
	$(MAKE) -C atom

$(OBJDIR)/main.o : main.f par.f $(OBJDIR)/modules.o
#helium/$(OBJDIR)/modules.o
	$(FC) $(aO1) -c main.f  -o $@

$(OBJDIR)/modules.o:  helium/modules.f
	$(FC) $a -c helium/modules.f -o $@

# The -O0 -C -g stops crashes in BORN ICS at high energies
#$(OBJDIR)/processt.o : processt.f par.f
#	$(FC) $a -O0 -c processt.f  -o $@
#	$(FC) $a -Mllvm -O0 -traceback -C -g -c processt.f  -o $@

$(OBJDIR)/posvmat.o : posvmat.f par.f par.pos $(OBJDIR)/modules.o
	$(FC) $a  -c posvmat.f  -o $@

$(OBJDIR)/new-posvmat.o : new-posvmat.f par.f par.pos $(OBJDIR)/modules.o
	$(FC) $a  -c new-posvmat.f  -o $@

$(OBJDIR)/cc.o : cc.f 
	$(FC) $a -O0 -c cc.f  -o $@


$(OBJDIR)/vmat.o : vmat.f $(OBJDIR)/modules.o
	$(FC) $a $(FCFLAGS_FAST) -c vmat.f  -o $@


$(OBJDIR)/logam.o : logam.f 
	$(FC) $a -O0 $(FCFLAGS_SAVE) -c logam.f  -o $@

$(OBJDIR)/rest.o : rest.f par.f $(OBJDIR)/modules.o
	$(FC) $a $(FCFLAGS_SAVE) -O0 -c rest.f  -o $@

$(OBJDIR)/corratom.o : corratom.f par.f paratom.f 
	$(FC) $a -c corratom.f  -o $@

$(OBJDIR)/gpuvdirect.o : gpuvdirect.f
#	pgf90 -Mllvm $(pga)  -mp -Minfo=accel,mp -acc -ta=tesla:cc35,cc50,cc60,nordc -mcmodel=medium -c gpuvdirect.f  -o $@
	$(FC) $(aGPU) -c gpuvdirect.f -o $@

$(OBJDIR)/first.o : first.f $(OBJDIR)/modules.o
#	pgf90 -Mllvm $(pga) -mp -O2 -Minfo=accel -acc -ta=tesla:cc35,cc50,cc60,nordc -mcmodel=medium -Mpreprocess -Iatom -Ihelium -Ihelium/$(OBJDIR) -module $(OBJDIR) -c  first.f -o $@
	$(FC) $(aGPU) -c first.f -o $@

$(OBJDIR)/form.o : form.f
#	pgf90 -Mllvm $(pga) -mp -O2 -Mnoinline -Minfo=accel -mcmodel=medium -c  form.f -o $@
	$(FC) $a $(FCFLAGS_FAST) -c form.f -o $@

$(OBJDIR)/jnt.o : jnt.f par.f paratom.f 
	$(FC) $a -c jnt.f  -o $@

$(OBJDIR):
	if ( test ! -d $@ ) then ( mkdir -p $@ ) fi

$(OBJDIR)/eremenko.o : eremenko.f90
	$(FC) $a -c eremenko.f90 -o $@

$(OBJDIR)/%.o : %.f par.f
	$(FC) $a -c $< -o $@

